# theme: minima # change to my own theme when ready
title: Ricardo Otero
email: oterosantos@gmail.com
description: Ricardo Otero homepage
twitter_username: rikas
github_username: rikas
linkedin_username: oterosantos
paginate: 5
paginate_path: '/page:num/'
plugins:
  - jekyll-analytics
jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: UA-8227995-3        # Required - replace with your tracking id
    anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking
